import { test, expect } from '@playwright/test';

/**
 * This test suite was created with the Playwright Test recorder
 * and then slightly modified to use methods which are not generated by the recorder
 * e.g. expect(page).toHaveTitle...
 * also some of the code generated by recorder is uneccessary, like page.getByLabel('Najít').click();
 * since the .fill() method doesn't require the element to be clicked first
 */
test('test', async ({ page }) => {
  await page.goto('https://www.google.com/');
  await page.getByRole('button', { name: 'Odmítnout vše' }).click();
  await page.getByLabel('Najít').click();
  await page.getByLabel('Najít').fill('cute puppies');
  await page.keyboard.press('Enter');
  await expect(page).toHaveTitle(/cute puppies/)
});